In [2]:
import numpy as np

In [9]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [10]:
print(array.shape)

(16,)


In [11]:
a = array.reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
print("array of shape:", a.shape)
print("dimension of array:", a.ndim)
print("data type:", a.dtype.name)
print("size:", a.size)
print("type",type(a))


array of shape: (4, 4)
dimension of array: 2
data type: int32
size: 16
type <class 'numpy.ndarray'>


In [15]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
print(array3.shape)

(4, 4)


In [19]:
zeros= np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
zeros[1,1]=6
print(zeros)

[[0. 0. 0.]
 [0. 6. 0.]]


In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty((3,4))

array([[1.22914476e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.01855798e-312, 1.54839721e+185, 9.39227126e+165,
        1.11599809e+165],
       [1.32732848e-075, 4.08795740e-037, 3.92081314e+179,
        6.52972072e-038]])

In [24]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
a = np.linspace(0,100,4)
print(a)

[  0.          33.33333333  66.66666667 100.        ]


In [27]:
a= np.array([1,2,3])
b= np.array([4,5,6])

print(a+b)
print(a-b)

[5 7 9]
[-3 -3 -3]


In [28]:
print(a**2)

[1 4 9]


In [29]:
list= [1,2,3,4,5]
array= np.array([11,12,13,14,15])

print(list)
print(array)


[1, 2, 3, 4, 5]
[11 12 13 14 15]


In [31]:
array = np.array(list)
print(array)

[1 2 3 4 5]


In [34]:
d = a.copy()

In [35]:
a= np.array([5,6,7,8,9])
print(a)

[5 6 7 8 9]


In [36]:
print(a[1:3])

[6 7]


In [38]:
reverse_array =a[::-1]
print (reverse_array)

[9 8 7 6 5]


In [39]:
print(a)

[5 6 7 8 9]


In [42]:
x = np.array([[0,1,2,3],[4,5,6,7]])
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [44]:
print(x[1,1])

5


In [45]:
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [47]:
print(x[1,1])

5


In [49]:
print(x[1,2])

6


In [50]:
print(x[1,2])

6


In [51]:
print(x[0,2],x[1,2])

2 6


In [52]:
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [53]:
x = array.ravel()
print(x)

[1 2 3 4 5]


In [54]:
print(x)

[1 2 3 4 5]


In [55]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
x = array.ravel()
print(x)

[1 2 3 4 5]


In [58]:
array3 = np.array([[1,1],[2,2],[3,3]])
print(array3)

[[1 1]
 [2 2]
 [3 3]]


In [60]:
array3.resize((1,2))
print(array3)

[[1 1]]


In [61]:
print(array3)

[[1 1]]


In [62]:
array_test = np.array([[1,2],[3,4],[5,6]])
print(array_test)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
array_test.resize((2,3))
print (array_test)

[[1 2 3]
 [4 5 6]]
